<div class="index-banner">
       	  <div class="wmuSlider example1" style="height: 560px;">
			  <div class="wmuSliderWrapper">
				  <article style="position: relative; width: 100%; opacity: 1;"> 
				   	<div class="banner-wrap">
					   	<div class="slider-left">
							<img src="<?php echo $this->basePath('images/banner1.jpg') ?>" alt=""/> 
						</div>
						 <div class="slider-right">
						    <h1>Shop On</h1>
						    <h2>BESTBUY</h2>
						    <p>Shop Best Buy for electronics, computers, appliances, cell phones, video games & more</p>
						    <div class="btn"><a href="ebay_displayStoreItemsURL.html?_storeName=officialbestbuy">Shop Now</a></div>
						 </div>
						 <div class="clear"></div>
					 </div>
					</article>
				   <article style="position: absolute; width: 100%; opacity: 0;"> 
				   	 <div class="banner-wrap">
					   	<div class="slider-left">
							<img src="<?php echo $this->basePath('images/banner2.jpg') ?>" alt=""/> 
						</div>
						 <div class="slider-right">
						    <h1>Sony</h1>
						    <h2>Xperia Tablet Z</h2>
						    <p>Buy it from Ebay</p>
						    <div class="btn"><a href="ebay_displayStoreItemsURL.html?_storeName=Official-Sony-Store&_cId%5B0%5D=171485">Shop Now</a></div>
						 </div>
						 <div class="clear"></div>
					 </div>
				   </article>
				   <article style="position: absolute; width: 100%; opacity: 0;">
				   	<div class="banner-wrap">
					   	<div class="slider-left">
							<img src="<?php echo $this->basePath('images/banner3.jpg') ?>" alt=""/> 
						</div>
						 <div class="slider-right">
						    <h1>Apple</h1>
						    <h2>Iphone 6 or 6 plus</h2>
						    <p>Grab It Now</p>
						    <div class="btn"><a href="ebay_displayURL.html?searchQuery=iphone6&_cId%5B0%5D=15032">Shop Now</a></div>
						 </div>
						 <div class="clear"></div>
					 </div>
				   </article>
				   <article style="position: absolute; width: 100%; opacity: 0;">
				   	<div class="banner-wrap">
					   	<div class="slider-left">
							<img src="<?php echo $this->basePath('images/banner4.jpg') ?>" alt=""/> 
						</div>
						 <div class="slider-right">
						    <h1>Microsoft</h1>
                                                    <h2 style="font-size: 2.5em">Surface Pro 3</h2>
						    <p>Buy it from Ebay</p>
						    <div class="btn"><a href="ebay_displayStoreItemsURL.html?_storeName=OfficialBestBuy&_cId%5B0%5D=171485&Brand=Microsoft&_pageNum=1">Shop Now</a></div>
						 </div>
						 <div class="clear"></div>
					 </div>
				   </article>
				   <article style="position: absolute; width: 100%; opacity: 0;"> 
				   	 <div class="banner-wrap">
					   	<div class="slider-left">
							<img src="<?php echo $this->basePath('images/banner5.jpg') ?>" alt=""/> 
						</div>
						 <div class="slider-right">
						    <h1>Calvin Klein</h1>
<!--						    <h2>Official eBay Store</h2>-->
						    <p>Everything you need for the season</p>
						    <div class="btn"><a href="ebay_displayStoreItemsURL.html?_storeName=Calvin-Klein">Shop Now</a></div>
						 </div>
						 <div class="clear"></div>
					 </div>
			      </article>
				</div>
                <a class="wmuSliderPrev">Previous</a><a class="wmuSliderNext">Next</a>
                <ul class="wmuSliderPagination">
                	<li><a href="#" class="">0</a></li>
                	<li><a href="#" class="">1</a></li>
                	<li><a href="#" class="wmuActive">2</a></li>
                	<li><a href="#">3</a></li>
                	<li><a href="#">4</a></li>
                  </ul>
                 <a class="wmuSliderPrev">Previous</a><a class="wmuSliderNext">Next</a><ul class="wmuSliderPagination"><li><a href="#" class="wmuActive">0</a></li><li><a href="#" class="">1</a></li><li><a href="#" class="">2</a></li><li><a href="#" class="">3</a></li><li><a href="#" class="">4</a></li></ul></div>
            	 <script src="<?php echo $this->basePath('js/jquery.wmuSlider.js') ?>"></script> 
				 <script type="text/javascript" src="<?php echo $this->basePath('js/modernizr.custom.min.js') ?>"></script> 
						<script>
       						 $('.example1').wmuSlider();         
   						</script> 	           	      
             </div>
             <div class="main">
                <div class="wrap">
             	  <div class="content-top">
             		<div class="lsidebar span_1_of_c1">
					  <p>Follow us on Social Platform</p>
					</div>
					<div class="cont span_2_of_c1">
					  <div class="social">	
					     <ul>	
                                                 <li class="facebook"><a href="http://www.facebook.com" target="_blank"><span> </span></a><div class="radius"> <img src="<?php echo $this->basePath('images/radius.png') ?>"><a href="#"> </a></div><div class="border hide"><p class="num">1.51K</p></div></li>
						 </ul>
			   		   </div>
					   <div class="social">	
						   <ul>	
							  <li class="twitter"><a href="#"><span> </span></a><div class="radius"> <img src="<?php echo $this->basePath('images/radius.png') ?>"></div><div class="border hide"><p class="num">1.51K</p></div></li>
						  </ul>
			     		</div>
						 <div class="social">	
						   <ul>	
							  <li class="google"><a href="#"><span> </span></a><div class="radius"> <img src="<?php echo $this->basePath('images/radius.png') ?>"></div><div class="border hide"><p class="num">1.51K</p></div></li>
						   </ul>
			    		 </div>
						 <div class="social">	
						   <ul>	
							  <li class="dot"><a href="#"><span> </span></a><div class="radius"> <img src="<?php echo $this->basePath('images/radius.png') ?>"></div><div class="border hide"><p class="num">1.51K</p></div></li>
						  </ul>
			     		</div>
						<div class="clear"> </div>
					  </div>
					  <div class="clear"></div>			
				   </div>
                    
                    <div class="content-middle" style="padding-bottom: 10px; font-weight: 600; font-size: 20px ">
                                      <h2>Popular Stores</h2>
                                  </div>
				  
                             <div class="content-bottom">
				   <div class="box1">
				  
<!--                              modified-->
<!--                            <div class="col_1_of_3 span_1_of_3"><a href="ebay_displayStoreItemsURL.html?_storeName=Acer">-->
                            <div class="col_1_of_3 span_1_of_3"><a href="<?php echo $this->url('usabaazar', array('action'=>'ebaystoredisplay'))."?_storeName=Acer"?>">
				     <div class="view view-fifth">
				  	  <div class="top_box">
					  	<h3 class="m_1">Acer Store</h3>
					  	<p class="m_2">Buy Tablets, PC, Laptops</p>
				         <div class="grid_img">
						   <div class="css3"><img src="<?php echo $this->basePath('images/Acer_logo.jpg') ?>" alt=""></div>
					          <div class="mask">
	                       		<div class="info">Go to Store</div>
			                  </div>
	                    </div>
                       
					   </div>
					    </div>
					   
						 </a>
			    	    <div class="clear"></div>
			    	</div>
                              
                              
                              
				    <div class="col_1_of_3 span_1_of_3"><a href="<?php echo $this->url('usabaazar', array('action'=>'ebaystoredisplay'))."?_storeName=microsoft-store"?>">
				     <div class="view view-fifth">
				  	  <div class="top_box">
					  	<h3 class="m_1">Microsoft Store</h3>
					  	<p class="m_2">Xbox, Surface 3 Tablet, PC, Office, Windows Phone</p>
				         <div class="grid_img">
						   <div class="css3"><img src="<?php echo $this->basePath('images/microsoft-store.jpg') ?>" alt=""></div>
					          <div class="mask">
	                       		<div class="info">Go to store</div>
			                  </div>
	                    </div>
                       
					   </div>
					    </div>
					   
						 </a>
			    	    <div class="clear"></div>
			    	</div>
				   <div class="col_1_of_3 span_1_of_3"><a href="<?php echo $this->url('usabaazar', array('action'=>'ebaystoredisplay'))."?_storeName=Official-Sony-Store"?>">
				     <div class="view view-fifth">
				  	  <div class="top_box">
					  	<h3 class="m_1">Official Sony eBay Store</h3>
					  	<p class="m_2">Electronics, PlayStation, Movies</p>
				         <div class="grid_img">
						   <div class="css3"><img src="<?php echo $this->basePath('images/sonylogo.jpg') ?>" alt=""></div>
					          <div class="mask">
	                       		<div class="info">Go to Store</div>
			                  </div>
	                    </div>
                       
					   </div>
					    </div>
					   
						 </a>
			    	    <div class="clear"></div>
			    	</div>
				  <div class="clear"></div>
			    </div>
                                      
                                      
			  <div class="box1">
				  
<!--                              modified-->
                            <div class="col_1_of_3 span_1_of_3"><a href="<?php echo $this->url('usabaazar', array('action'=>'ebaystoredisplay'))."?_storeName=GUESS-outlet"?>">
				     <div class="view view-fifth">
				  	  <div class="top_box">
					  	<h3 class="m_1">Guess Outlet</h3>
					  	<p class="m_2">on eBay</p>
				         <div class="grid_img">
						   <div class="css3"><img src="<?php echo $this->basePath('images/guess_logo.jpg') ?>" alt=""></div>
					          <div class="mask">
	                       		<div class="info">Go to Store</div>
			                  </div>
	                    </div>
                       
					   </div>
					    </div>
					   
						 </a>
			    	    <div class="clear"></div>
			    	</div>
                              
                              
                              
				    <div class="col_1_of_3 span_1_of_3"><a href="<?php echo $this->url('usabaazar', array('action'=>'ebaystoredisplay'))."?_storeName=Toshiba-Direct-Store"?>">
				     <div class="view view-fifth">
				  	  <div class="top_box">
					  	<h3 class="m_1">Toshiba</h3>
					  	<p class="m_2">Laptops, Netbooks</p>
				         <div class="grid_img">
						   <div class="css3"><img src="<?php echo $this->basePath('images/toshiba-logo.jpg') ?>" alt=""></div>
					          <div class="mask">
	                       		<div class="info">Go to Store</div>
			                  </div>
	                    </div>
                       
					   </div>
					    </div>
					   
						 </a>
			    	    <div class="clear"></div>
			    	</div>
				   <div class="col_1_of_3 span_1_of_3"><a href="<?php echo $this->url('usabaazar', array('action'=>'ebaystoredisplay'))."?_storeName=beats-certified-outlet"?>">
				     <div class="view view-fifth">
				  	  <div class="top_box">
					  	<h3 class="m_1">beats by dr. dre</h3>
					  	<p class="m_2">Headphones, Earphones, Speakers</p>
				         <div class="grid_img">
						   <div class="css3"><img src="<?php echo $this->basePath('images/beats-by-dr-dre-logo.jpg') ?>" alt=""></div>
					          <div class="mask">
	                       		<div class="info">Go to the store</div>
			                  </div>
	                    </div>
                       
					   </div>
					    </div>
					   
						 </a>
			    	    <div class="clear"></div>
			    	</div>
				  <div class="clear"></div>
			    </div>
			  </div>
			 </div>
        </div>